#ifndef CONFIG_H
#define CONFIG_H
#define SDA_PIN 3
#define SCL_PIN 4
#define MAX_INT 5
#define LED_BRIGHTNESS 0xFF
#define SAMPLE_AVERAGE 4
#define LED_MODE 2
#define SAMPLE_RATE 100
#define PULSE_WIDTH 411
#define ADC_RANGE 16384
#define BATTERY_INDICATOR 1

typedef enum {
    SYSTEM_CHECK,
    SYSTEM_END,
    SYSTEM_NORMAL,
    SYSTEM_EXCEEDED_TRIALS
} SYSTEM_CASES;
#endif